name: FMCSA Dispatcher (All Batches)

on:
  # Manual run ke liye (Run workflow button)
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Number of MCs per batch'
        required: false
        default: '500'
  
  # API se trigger hone ke liye (frontend se)
  repository_dispatch:
    types: [run-dispatcher-from-frontend]

jobs:
  dispatch-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create_jobs.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Split mc_list.txt into batches
        id: create_jobs
        run: |
          if [ ! -f mc_list.txt ]; then
            echo "mc_list.txt not found!"
            exit 1
          fi
          
          mkdir -p .batches
          # Agar frontend se batch_size aaya hai to usay istemal karo, warna default
          BATCH_SIZE=${{ github.event.client_payload.batch_size || github.event.inputs.batch_size }}
          split -l $BATCH_SIZE mc_list.txt .batches/mc_batch_
          
          # 'jq' ka istemal karke single-line JSON banayein
          JSON_CONTENT=$(ls .batches/mc_batch_* | jq -R '{"batch_file": .}' | jq -s '{"include": .}')
          
          echo "Generated Matrix:"
          echo $JSON_CONTENT
          echo "matrix=$JSON_CONTENT" >> $GITHUB_OUTPUT

  trigger-extractors:
    needs: dispatch-jobs
    runs-on: ubuntu-latest
    if: ${{ needs.dispatch-jobs.outputs.matrix != '{"include":[]}' }}

    strategy:
      matrix: ${{ fromJson(needs.dispatch-jobs.outputs.matrix) }}

    steps:
      - name: Trigger extractor for batch ${{ matrix.batch_file }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: run-single-fmcsa-batch
          client-payload: '{"batch_file_path": "${{ matrix.batch_file }}"}'
