name: FMCSA Dispatcher (All Batches)

# --- YAHAN ASAL TABDEELI HAI ---
# Humne 'repository_dispatch' ka naya darwaza add kar diya hai
on:
  # Yeh aapka purana, manual trigger hai (yeh abhi bhi kaam karega)
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Batch size per run'
        required: false
        default: '250'
  
  # Yeh naya, automatic trigger hai jo dashboard se call hoga
  repository_dispatch:
    types: [run-fmcsa-job-from-frontend]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Split mc_list into batches
        run: |
          mkdir -p batches
          # Hum yahan 'github.event.inputs.batch_size' ka istemal kar rahe hain
          # Agar manual run hai to user ki value, warna default 250
          split -l ${{ github.event.inputs.batch_size || '250' }} mc_list.txt batches/batch_
          ls -l batches

      - name: Dispatch extractor for each batch
        env:
          # Yahan PAT_TOKEN istemal ho raha hai, isay repository secrets mein laazmi add karein
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          i=0
          for f in batches/*; do
            echo "Dispatching batch $f (index $i)..."
            gh workflow run extractor.yml \
              --ref main \
              -f batch_index=$i \
              -f batch_size=${{ github.event.inputs.batch_size || '250' }} \
              -f concurrency=4 \
              -f delay=1000 \
              -f wait_seconds=0 \
              -f mode=both
            i=$((i+1))
          done
