name: 1. FMCSA Dispatcher

on:
  repository_dispatch:
    types: [run-fmcsa-job-from-frontend]
  workflow_dispatch:

jobs:
  dispatch-extractors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Split MC list into chunks and dispatch jobs
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # mc_list.txt ko 250 lines ki temporary files mein taqseem karo
          split -l 250 mc_list.txt temp_batch_

          # Har banayi gayi temporary file ke liye ek job trigger karo
          for file in temp_batch_*; do
            # File ke andar mojood tamam MC numbers ko parh kar, unhein comma se jor kar ek lambi string banao
            MC_CHUNK=$(paste -s -d, "$file")
            
            echo "Dispatching extractor job for a chunk of MC numbers..."
            
            # Hum ab file ka path nahi, balke MC numbers ki poori string bhej rahe hain
            gh workflow run extractor.yml --ref main -f mc_numbers="$MC_CHUNK"
            
            sleep 1 # API rate limit se bachne ke liye
          done
