name: FMCSA Dispatcher Workflow

on:
  repository_dispatch:
    types: [run-dispatcher-from-frontend]

jobs:
  dispatch-fmcsa-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the main dispatcher script
        run: python dispatcher.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
