name: FMCSA Dispatcher Workflow

on:
  repository_dispatch:
    types: [run-dispatcher-from-frontend]

jobs:
  dispatch-fmcsa-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- YAHAN ASAL TABDEELI HAI ---
      # Hum ab direct Python script ko chala rahe hain.
      # Python script ab khud hi doosre workflow ko trigger karegi.
      - name: Run the main dispatcher script
        run: python main.py
        env:
          # Hum yahan apni "master key" ko Python script ke hawale kar rahe hain
          # taake woh isay istemal karke, doosre workflows ko trigger kar sake.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
