name: FMCSA Dispatcher (All Batches)

on:
  # Manual run ke liye (Run workflow button)
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Number of MCs per batch'
        required: false
        default: '500'
  
  # API se trigger hone ke liye (frontend se)
  repository_dispatch:
    types: [run-dispatcher-from-frontend]

jobs:
  # JOB 1: Batches banana aur agle job ke liye matrix tayyar karna
  dispatch-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create_jobs.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Split mc_list.txt into batches and create jobs
        id: create_jobs
        run: |
          # Agar mc_list.txt mojood nahi hai to error de kar ruk jao
          if [ ! -f mc_list.txt ]; then
            echo "mc_list.txt not found!"
            exit 1
          fi
          
          mkdir -p .batches
          # Agar frontend se batch_size aaya hai to usay istemal karo, warna default
          BATCH_SIZE=${{ github.event.client_payload.batch_size || github.event.inputs.batch_size }}
          split -l $BATCH_SIZE mc_list.txt .batches/mc_batch_
          
          # 'jq' tool ka istemal karke ek single-line JSON banayein
          JSON_CONTENT=$(ls .batches/mc_batch_* | jq -R '{"batch_file": .}' | jq -s '{"include": .}')
          
          echo "Generated Matrix:"
          echo $JSON_CONTENT
          
          # Result ko GitHub output mein set karein
          echo "matrix=$JSON_CONTENT" >> $GITHUB_OUTPUT

  # JOB 2: Har batch ke liye extractor ko trigger karna
  trigger-extractors:
    needs: dispatch-jobs # Pehle job ke mukammal hone ka intezar karein
    runs-on: ubuntu-latest
    
    # Agar koi batch file na bane to is job ko na chalao
    if: ${{ needs.dispatch-jobs.outputs.matrix != '{"include":[]}' }}

    strategy:
      matrix: ${{ fromJson(needs.dispatch-jobs.outputs.matrix) }}

    steps:
      - name: Trigger extractor for batch ${{ matrix.batch_file }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: run-single-fmcsa-batch
          client-payload: '{"batch_file_path": "${{ matrix.batch_file }}"}'
