name: 2. FMCSA Extractor

on:
  workflow_dispatch:
    inputs:
      batch_file_path:
        description: 'The path to the batch file to process'
        required: true

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper for the given batch file
        run: python scraper.py ${{ github.event.inputs.batch_file_path }}

      - name: Upload results as an artifact
        uses: actions/upload-artifact@v4
        with:
          # Hum poore output folder ko artifact bana rahe hain
          name: fmcsa-raw-results-${{ github.run_id }}
          path: output/
          if-no-files-found: ignore
