name: FMCSA Extractor (Single Batch)

on:
  # Isay ab sirf API (repository_dispatch) se hi chalaya ja sakta hai
  repository_dispatch:
    types: [run-single-fmcsa-batch]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get batch file path from payload
        id: get_payload
        run: |
          batch_path=$(echo '${{ github.event.client_payload.batch_file_path }}' | jq -r '.')
          echo "Processing batch file: $batch_path"
          echo "batch_file=$batch_path" >> $GITHUB_OUTPUT

      - name: Rename batch file for script
        run: mv ${{ steps.get_payload.outputs.batch_file }} batch.txt

      - name: Run extractor for this batch
        run: |
          node -v
          mkdir -p output
          node extractor.js
        env:
          CONCURRENCY: 4
          DELAY: 1000
          MODE: 'both'

      - name: Commit and Push CSV output
        if: always()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add output/*.csv
          git diff --staged --quiet || git commit -m "Add FMCSA scrape results for batch"
          git push
