name: FMCSA Extractor (Single Batch)

on:
  repository_dispatch:
    types: [run-single-fmcsa-batch]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create batch.txt from payload
        id: create_batch
        run: |
          # 'dispatcher.yml' se bheje gaye MC numbers ko batch.txt mein likhna
          echo "${{ github.event.client_payload.mc_numbers }}" > batch.txt
          echo "Created batch.txt with $(wc -l < batch.txt) MC numbers."

      - name: Run extractor for this batch
        run: |
          node -v
          mkdir -p output
          # extractor.js ab is nayi bani hui batch.txt se data parhega
          node extractor.js
        env:
          CONCURRENCY: 4
          DELAY: 1000
          MODE: 'both'

      - name: Commit and Push CSV output
        if: always()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add output/*.csv
          if ! git diff --staged --quiet; then
            git commit -m "Add FMCSA scrape results"
            git push
          else
            echo "No new CSV files to commit."
          fi
