name: FMCSA Data Extractor

on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Batch number to process'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- YAHAN ASAL, AAKHRI TABDEELI HAI ---
      - name: Run scraper
        run: python src/scraper.py ${{ github.event.inputs.batch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmcsa-leads-batch-${{ github.event.inputs.batch }}
          path: output/fmcsa_data_${{ github.event.inputs.batch }}.csv
